[monitors]
left = "DP-5"
right = "DP-3"
# The position is such that the bottom of the screens align taking scale into account
left_config = "resolution 1920x1200 position 0,0"
right_config = "resolution 1920x1200 position 1920,0"
additional = "output eDP-1 disable"
