# Path to your dotfile directory containing this config file (relative to $HOME).
dotfiles_dir = "dotfiles"

gpg_user_id = "alexander.loitzl@gmail.com"

[settings]
posthooks = [ "sway reload" ]
vars = [ "secrets.toml" ]

# Dotfiles template with their respective `source` template and `target` directories.
[settings.dots]
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.
sway = { source = "sway/config", target = ".config/sway", vars = "sway/vars.toml" }
doom = { source = "doom", target = ".config/doom" }
i3status-rust = { source = "i3status-rust", target = ".config/i3status-rust" }
alacritty = { source = "alacritty", target = ".config/alacritty" }

[profiles.work.dots]
sway = {source ="sway/config", target = ".config/sway", vars = "sway/work-vars.toml"}
